openapi: 3.0.1
info:
  title: Simple Microblog Service
  description: "API service used for testing experimental backend architectures."
  termsOfService: http://omega.io/terms/
  contact:
    email: apiteam@omega.io
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
  x-application-config:
    docker:
      service-name: microblog-service-backend
    aws:
      ecr-repository-name: my-microblog-service
      ecs-service-name: api-my-microblog-service
servers:
  - url: https://microblog.omega.io/v2
  - url: http://microblog.omega.io/v2
tags:
  - name: Posts
    description: Endpoints for accessing Posts business services.
paths:
  /posts:
    post:
      tags:
        - Posts
      summary: Create new post.
      operationId: createPost
      security:
        - microblogservice_auth:
            - create:any
            - create:own
    get:
      tags:
        - Posts
      summary: Get all post documents from the data store.
      description: Get all post documents from the data store.
      operationId: getAllPosts
      security:
        - microblogservice_auth:
            - read:any
            - read:own
  /posts/{id}:
    put:
      tags:
        - Posts
      summary: Update an existing post.
      operationId: updatePost
      security:
        - microblogservice_auth:
            - update:any
            - update:own
    get:
      tags:
        - Posts
      summary: Find a single post by UUID.
      description: Find a single post document by its UUID.
      operationId: findPostById
      security:
        - microblogservice_auth:
            - read:any
            - read:own
    delete:
      tags:
        - Posts
      summary: Delete an existing post.
      operationId: deletePost
      security:
        - microblogservice_auth:
            - delete:any
  /users:
    post:
      tags:
        - Users
      summary: Create new user.
      operationId: createUser
      security:
        - microblogservice_auth:
            - create:any
            - create:own
    get:
      tags:
        - Users
      summary: Get all user documents from the data store.
      description: Get all user documents from the data store.
      operationId: getAllUsers
      security:
        - microblogservice_auth:
            - read:any
            - read:own
  /users/{id}:
    put:
      tags:
        - Users
      summary: Update an existing user.
      operationId: updateUser
      security:
        - microblogservice_auth:
            - update:any
            - update:own
    get:
      tags:
        - Users
      summary: Find a single user by UUID.
      description: Find a single user document by its UUID.
      operationId: findUserById
      security:
        - microblogservice_auth:
            - read:any
            - read:own
    delete:
      tags:
        - Users
      summary: Delete an existing user.
      operationId: deleteUser
      security:
        - microblogservice_auth:
            - delete:any
  /token:
    post:
      tags:
        - Token
      summary: Create new authentication token.
      operationId: createToken
components:
  securitySchemes:
    microblogservice_auth:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: http://petstore.swagger.io/oauth/dialog
          scopes:
            write:beers: modify beers in your account
            read:beers: read your beers
    api_key:
      type: apiKey
      name: api_key
      in: header
